model = "gpt-5.6-sol"
model_reasoning_effort = "high"
personality = "pragmatic"

[projects."/Users/fcote/Code/pp-cf"]
trust_level = "trusted"

[projects."/Users/fcote/Code/freefonts-xyz"]
trust_level = "trusted"

[projects."/Users/fcote/Code/fontly"]
trust_level = "trusted"

[projects."/Users/fcote/.dotfiles"]
trust_level = "trusted"

[tui]
status_line = ["current-dir", "git-branch", "model-with-reasoning", "context-used", "five-hour-limit", "weekly-limit"]
status_line_use_colors = true

[tui.model_availability_nux]
"gpt-5.5" = 4
"gpt-5.6-sol" = 1


[features]
experimental_use_rmcp_client = true
hooks = true
memories = true

[hooks.state]

[hooks.state."/Users/fcote/.codex/hooks.json:pre_tool_use:0:0"]
trusted_hash = "sha256:ccce2a964c2c04a98fabc1c86b5db4424a39842fea493c8913ca6578cbb5d396"

[hooks.state."/Users/fcote/.codex/hooks.json:permission_request:0:0"]
trusted_hash = "sha256:cada6d00a329cf92d3f897573962c076b2c9e177ffde17df5283b6e12683b53f"

[hooks.state."/Users/fcote/.codex/hooks.json:session_start:0:0"]
trusted_hash = "sha256:bf08cf7080427e1b82a166c7d3a1eaf570c1147aba306a764fd89707dcd89690"
enabled = true

[hooks.state."/Users/fcote/.codex/hooks.json:user_prompt_submit:0:0"]
trusted_hash = "sha256:64d4baf45d86725d53fc495ab70533ecc0cba087ee2290746f57285b71f59c2e"

[hooks.state."/Users/fcote/.codex/hooks.json:stop:0:0"]
trusted_hash = "sha256:f9bfac1abe13022c3863598923c7e1a5937d8510136df38bab76d0c3989192e7"

[mcp_servers.linear]
url = "https://mcp.linear.app/mcp"

[mcp_servers.figma]
url = "https://mcp.figma.com/mcp"
