gui:
  statusPanelView: allBranchesLog
  skipDiscardChangeWarning: true
  theme:
    selectedLineBgColor:
      - reverse
  nerdFontsVersion: "3"
  commitAuthorLongLength: 2
git:
  diffRenderers:
    - colorArg: always
      command: delta --light --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
  log:
    showWholeGraph: true
customCommands:
  - key: 'V'
    context: 'commits'
    command: 'git revert --no-commit {{.SelectedLocalCommit.Sha}}'
    description: 'Revert commit without committing changes'
    output: terminal
