onboarding = false

[experimental]
kitty_graphics = true

[ui]
show_agent_labels_on_pane_borders = true

agent_panel_sort = "spaces"
[ui.sidebar.spaces]
row_gap = 0

[ui.sidebar.agents]
row_gap = 0

[ui.sound]
enabled = true

[ui.toast]
delivery = "terminal"

[theme]
name = "catppuccin-latte"
auto_switch = true
light_name = "catppuccin-latte"
dark_name = "catppuccin"

[keys]
prefix = "ctrl+a"

split_vertical = "prefix+|"

focus_pane_left = "shift+left"
focus_pane_down = "shift+down"
focus_pane_up = "shift+up"
focus_pane_right = "shift+right"

rename_tab = "prefix+comma"
rename_workspace = "prefix+period"

previous_tab = "ctrl+left"
next_tab = "ctrl+right"
move_tab_previous = "ctrl+shift+left"
move_tab_next = "ctrl+shift+right"

previous_workspace = "ctrl+up"
next_workspace = "ctrl+down"
previous_agent = "ctrl+shift+up"
next_agent = "ctrl+shift+down"

goto = "prefix+/"

[[keys.command]]
key = "prefix+g"
type = "popup"
command = "lazygit"
description = "run lazygit"
width = "90%"
height = "90%"

[[keys.command]]
key = "prefix+l"
type = "popup"
command = "lazygit log --screen-mode full"
description = "run lazygit log"
width = "90%"
height = "90%"

[[keys.command]]
key = "prefix+i"
type = "popup"
command = "exec \"${SHELL:-sh}\""
description = "open scratch terminal"
width = "90%"
height = "90%"
