session_name: configs
start_directory: ~/code/configs
windows:
- window_name: dotfiles
  layout: main-vertical
  start_directory: ~/.dotfiles
  panes:
  - null
- window_name: configs
  layout: main-vertical
  panes:
  - null
  - null
