#!/bin/sh
# Copies a list of MySQL databases
# this script requires that you load $mysql_u and $mysql_p variables from a
# local config file.
source $HOME/.localrc

# backup location
backup_location="$HOME/Code/_Backups/_MySQL"

# db is defined in .localrc

for db in ${dbs[@]}
    do
        echo "Backuping $db ... ";
        mysqldump -u $mysql_u -p$mysql_p $db | gzip -9 > $backup_location/$db.sql.gz
done

echo "DONE!"
